language: generic

sudo: required
services:
  - docker


before_install:
  - docker build -t typeblkcofe/docker-react -f Dockerfile.dev .

script:
  - sh "echo 'WE ARE DONE IN FIRST STAGE'"
  - docker run -e CI=true typeblkcofe/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region:   "us-east-1"
  app:      "docker-react"
  env:      "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-884769119230"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_MINE"
  secret_access_key: "$AWS_SECRET_KEY_MINE"


